####### BIBS ORDERED FOR DISPLAYING KOHA ITEMS ###################
#################################################################################

BIBS_ORDER = {'LASH': 1,
                'DROIT': 2,
                "SJA": 3,
                'SCIEN': 4,
                'MEDP': 5,
                'STAPS': 6,
                'LCSOPHIA': 7,
                'BIUTF': 8,
                'BIUTM': 9,
                'BIUTC': 10,
                'VA': 11,
                'OCANI': 12,
                'OCAVV': 13,
                'OCASA': 14,
                'JAD': 15,
                'LIRCE': 16,
                'CMMC': 17,
                'BCL': 18
                }
BIBS_ORDER_BY_LABEL = {"BU Lettres Arts Sciences Humaines": 1,
                "BU Droit et Science politique": 2,
                "BU Saint-Jean d’Angély": 3,
                "BU Sciences": 4,
                "BU Médecine": 5,
                "BU STAPS": 6,
                "Learning Center SophiaTech": 7,
                "Bibliothèque de l’IUT Fabron": 8,
                "Bibliothèque de l’IUT de Menton": 9,
                "BIUTC": 10,
                "VA": 11,
                "OCANI": 12,
                "OCAVV": 13,
                "OCASA": 14,
                "JAD": 15,
                "LIRCE": 16,
                "CMMC": 17,
                "BCL": 18
                }
