####### DICTIONNAIRES DE MAPPING POUR LES DONNEES CODEES KOHA ###################
#################################################################################

## 17/05/2025 : ajout de la localisation MAGASE
## 27/05/2025 : ajout des bibliothèques (GEORGEV et LIEGEARD) et localisations (JEUNESSE, LUDO, SONORE, VITRINE) de l'INSPE de Nice

MAPPING_CODES_TYPES_PRET = {'NOR': 'Prêt normal',
                            'COU': 'Prêt court',
                            'SP': 'Consultable sur place',
                            'RDV': 'Consultable sur place sur rendez-vous',
                            'NC': 'Non consultable',
                            'PCCOU': 'PC prêt 1j',
                            'PCLONG': 'PC prêt long',
                            'PCPRO': 'PC prêt professionnel',
                            'EL': 'En ligne',
                            'JEU' : 'Jeu de société'}
MAPPING_BIBS = {"LASH": "BU Lettres Arts Sciences Humaines",
                "DROIT": "BU Droit et Science politique",
                "SJA": "BU Saint-Jean d’Angély",
                "SCIEN": "BU Sciences",
                "MEDP": "BU Médecine",
                "STAPS": "BU STAPS",
                "GEORGEV": "Bibliothèque George V",
                "LIEGEARD": "Bibliothèque Liégeard",
                "LCSOPHIA": "Learning Center SophiaTech",
                "BIUTF": "Bibliothèque de l’IUT Fabron",
                "BIUTM": "Bibliothèque de l’IUT de Menton",
                "BIUTC": "Bibliothèque de l’IUT de Cannes",
                "VA": "Bibliothèque de la Villa Arson",
                "OCANI": "Bibliothèque de l’OCA Mont Gros",
                "OCAVV": "Bibliothèque de l’OCA Lagrange",
                "OCASA": "Bibliothèque de l’OCA Géoazur",
                "JAD": "Bibliothèque du LJAD",
                "LIRCE": "Bibliothèque du LIRCES",
                "CMMC": "Bibliothèque du CMMC",
                "BCL": "Bibliothèque du BCL",
                "BIBEL" : "Bibliothèque électronique"}
MAPPING_LOCS = {"A213E": "Salle A213 - Enseignement-Vulgarisation",
"A213G": "Salle A213 - Guides-Dico",
"A213I": "Salle A213 - Informatique",
"A213O": "Salle A213 - Ouvrages",
"A213P": "Salle A213 - Revues",
"A214": "Salle A214",
"A216C": "Salle A216 - Cartes-Atlas",
"A216P": "Salle A216 - Revues",
"A216T": "Salle A216 - Thèses-Mémoires",
"AFFICHES": "Affiches",
"AGM": "1er étage - Agrégation Maths",
"ARC": "Archives",
"ASE": "RDC - Fonds ASEMI",
"ATE": "Ateliers Villa Arson",
"BCL": "Bât. Horloge",
"BDOC": "Bureau documentation",
"BDP": "Accueil",
"BDVIDEO": "DVD, Vidéos, BD",
"BGG": "Fonds Gabriel Germain – Bibliothèque personnelle",
"BOSCO": "Fonds Henri Bosco - Bibliothèque personnelle",
"BP0": "RDC - Bureau de prêt",
"BUR": "Bureau",
"BUR2": "Bureau de prêt",
"BUR3": "Bureau",
"BUR4": "Bureau",
"CA": "Casque audio (à l'accueil)",
"CAL": "Calern",
"CAR": "RDC - Cartes",
"CDR1": "RDC - Accueil",
"CDS": "CD-ROM",
"CHATT": "Fonds Chatterji",
"CLT": "RDC - Romans et BD",
"CM": "PC portables (à l'accueil)",
"CMMC": "CMMC",
"CO": "Compactus",
"CONC" : "RDC - Concours",
"CODE": "Etage (SA2) - Codes",
"DET": "Détente",
"DET0": "RDC - Détente",
"DET1": "1er étage - Espace détente",
"DET2": "Salle de détente",
"DET3": "Fonds détente",
"DOC": "1er étage - Documentation professionnelle",
"DOCEL": "RDC - Bureau de prêt",
"DRO": "1er étage",
"ECO": "1er étage",
"EDN": "EDN",
"ENS": "Salle de lecture",
"EPS7": "Dossiers EPS",
"ES": "Espace Sécurisé (PC portables)",
"ETHIQ": "Ethique en santé",
"FLE": "1er étage - Fonds FLE",
"FP1": "Fonds patrimoniaux (1er étage)",
"FP2": "Fonds patrimoniaux (magasin)",
"FPAT": "Magasins - Fonds patrimoniaux",
"FS": "Fonds spécial",
"GEST": "1er étage",
"IDEM": "Magasins",
"IFSI": "Sciences infirmières",
"JEUNESSE": "Jeunesse",
"KINE": "RDC - Kinésithérapie",
"LANG7": "Espace Langues",
"LAS": "LAS",
"LELEC": "Livres électroniques en ligne",
"LIRCE": "LIRCES",
"LLA": "Magasins-Fonds LLAOR",
"LUDO": "Ludothèque",
"MAG": "Magasins",
"MAG2": "Magasins (sous-sol)",
"MAGASE": "Magasins",     
"MAN": "RDC - Manuels",
"MED": "RDC",
"MELEC": "Mémoires électroniques",
"MEM": "Mémoires (bacs)",
"MEZA": "Mezzanine-Atlas",
"MEZO": "Mezzanine - Ouvrages anciens",
"MLC": "Magasins",
"MM7": "Mémoires (Salle de lecture)",
"MSH": "2e étage - bibliothèque de recherche",
"ODONT": "RDC - Odontologie",
"ODYS": "RDC - Fonds Société et environnement",
"ORTHO": "Orthophonie",
"PDCTG": "RDC (SA1) - Presse",
"PDMAG": "Magasins",
"PDSA0": "Sous-sol (SA0) - Revues",
"PDSA1": "RDC (SA1) - Revues",
"PDSA2": "Etage (SA2) - Revues",
"PDSDR": "Sous-sol - Revues - Salle de recherche",
"PELEC": "Périodiques électroniques",
"PER7": "Revues",
"PERS": "Revues",
"PHALL": "Hall - Périodiques",
"PJEC2": "2e étage - revues d'Economie et Gestion",
"PJECM": "Magasins",
"PJECO": "1er étage",
"PJODM": "Magasins",
"PJODO": "RDC - Odontologie",
"PJPRS": "RDC - Presse",
"PJSOC": "2e étage - revues de Sociologie",
"PKINE": "RDC - Kinésithérapie",
"PLASE": "Magasins- Fonds ASEMI - Revues",
"PLIDE": "2e étage - revues Fonds IDERIC",
"PLLLA": "Magasins - Fonds LLAOR - Revues",
"PLMG1": "Magasins - Revues",
"PLMG2": "Magasins - Compactus",
"PMMAG": "Magasins",
"PMPAS": "Revues",
"PREF0": "Hall - Kiosque",
"PSBUR": "RDC Bureau Catalogage - Revues",
"PSMG2": "Magasins - Revues",
"PSNI2": "1er étage - Revues",
"PSPRS": "RDC - Presse",
"RDC": "Rez de chaussée",
"RE1": "RDC - Dictionnaires",
"RE2": "1er étage - Dictionnaires",
"REF0": "RDC - Dictionnaires",
"REF1": "1er étage - Dictionnaires",
"RF7": "Espace Langues",
"RFS": "Dictionnaires",
"RUS": "Rustrel",
"SA0": "Sous-sol",
"SA1": "RDC",
"SA2": "Etage",
"SCPO": "1er étage",
"SDR": "Sous-sol - Salle de recherche",
"SHL": "RDC",
"SL": "Salle de lecture",
"SL1": "RDC",
"SL2": "1er étage",
"SL7": "Salle de lecture",
"SLC": "Salle de lecture - Collections",
"SLO": "Salle de lecture - Ouvrages",
"SLP": "Salle de lecture - Revues",
"SLT": "Salle de lecture - Thèses-Mémoires",
"SLU": "Salle de lecture - Usuels-Doc. OCA",
"SONORE": "Fonds sonore",
"SS1O": "Sous-sol 1 - Ouvrages",
"SS1P": "Sous-sol 1 - Revues",
"SS2": "Sous-sol 2",
"ST": "RDC",
"TELEC": "Thèses électroniques",
"TH7": "Thèses (Salle de lecture)",
"THECO": "Magasins",
"THLAS": "Magasins",
"THODO": "Magasins",
"URF": "Urfist",
"US": "Usuels",
"US0": "Sous-sol (SA0) - Dictionnaires",
"US1": "RDC (SA1) - Dictionnaires",
"US2": "Etage (SA2) - Dictionnaires",
"VITRINE": "Vitrine"

}
