####### DICTIONNAIRES DE MAPPING POUR LES DONNEES CODEES KOHA ###################
#################################################################################

MAPPING_CODES_TYPES_PRET = {'NOR': 'Prêt normal - 14 jours',
                            'COU': 'Prêt court - 5 jours'}
MAPPING_BIBS = {"LASH": "BU Lettres Arts Sciences Humaines",
                "DROIT": "BU Droit et Science politique",
                "SJA": "BU Saint-Jean d’Angély",
                "SCIEN": "BU Sciences",
                "MEDP": "BU Médecine",
                "STAPS": "BU STAPS",
                "LCSOPHIA": "Learning Center SophiaTech",
                "BIUTF": "Bibliothèque de l’IUT Fabron",
                "BIUTM": "Bibliothèque de l’IUT de Menton",
                "BIUTC": "Bibliothèque de l’IUT de Cannes",
                "VA": "Bibliothèque de la Villa Arson",
                "OCANI": "Bibliothèque de l’OCA Mont Gros",
                "OCAVV": "Bibliothèque de l’OCA Lagrange",
                "OCASA": "Bibliothèque de l’OCA Géoazur",
                "JAD": "Bibliothèque du LJAD",
                "LIRCE": "Bibliothèque du LIRCES",
                "CMMC": "Bibliothèque du CMMC",
                "BCL": "Bibliothèque du BCL"}
MAPPING_LOCS = {"A213E": "Salle A213 - Enseignement-Vulgarisation",
"A213G": "Salle A213 - Guides-Dico",
"A213I": "Salle A213 - Informatique",
"A213O": "Salle A213 - Ouvrages",
"A213P": "Salle A213 - Revues",
"A214": "Salle A214",
"A216C": "Salle A216 - Cartes-Atlas",
"A216P": "Salle A216 - Revues",
"A216T": "Salle A216 - Thèses-Mémoires",
"AGM": "1er étage - Agrégation Maths [AGM]",
"ARC": "Archives [ARC]",
"ASE": "RDC - Fonds ASEMI [ASE]",
"ATE": "Ateliers Villa Arson [ATE]",
"BCL": "Bât. Horloge [BCL]",
"BDOC": "Bureau documentation [BDOC]",
"BDP": "Bureau de prêt [BDP]",
"BDVIDEO": "DVD, Vidéos, BD [BDVIDEO]",
"BOSCO": "Fonds Henri Bosco - Bibliothèque personnelle [BOSCO]",
"BP0": "RDC - Bureau de prêt [BP0]",
"BUR": "Bureau [BUR]",
"BUR2": "Bureau de prêt [BUR2]",
"BUR3": "Bureau Catalogage RDC [BUR3]",
"BUR4": "Bureau 1er étage [BUR4]",
"CA": "Casque audio (en BDP) [CA]",
"CAL": "Calern [CAL]",
"CAR": "RDC - Cartes [CAR]",
"CDR1": "Bureau de prêt - CD-ROM [CDR1]",
"CDS": "CD-ROM [CDS]",
"CHATT": "Fonds Chatterji [CHATT]",
"CLT": "RDC - Romans et BD [CLT]",
"CM": "Classe mobile (PC portable en BDP) [CM]",
"CMMC": "CMMC",
"CO": "Compactus [CO]",
"CODE": "Etage (SA2) - Codes [CODE]",
"DET": "Détente [DET]",
"DET0": "RDC - Détente [DET0]",
"DET1": "1er étage - Espace détente [DET1]",
"DOC": "1er étage - Documentation professionnelle [DOC]",
"DOCEL": "RDC - Bureau de prêt [DOCEL]",
"DRO": "1er étage [DRO]",
"ECO": "1er étage [ECO]",
"EDN": "EDN [EDN]",
"ENS": "Salle de lecture [ENS]",
"EPS7": "Dossiers EPS [EPS7]",
"ES": "Espace Sécurisé (PC portables) [ES]",
"ETHIQ": "Ethique en santé [ETHIQ]",
"FLE": "1er étage - Fonds FLE [FLE]",
"FP1": "Fonds patrimoniaux (1er étage) [FP1]",
"FP2": "Fonds patrimoniaux (MAG) [FP2]",
"FPAT": "Magasins - Fonds patrimoniaux [FPAT]",
"FS": "Fonds spécial [FS]",
"GEST": "1er étage [GEST]",
"IDEM": "Magasins [IDEM]",
"IFSI": "Sciences infirmières [IFSI]",
"KINE": "RDC - Kinésithérapie [KINE]",
"LANG7": "Espace Langues [LANG7]",
"LAS": "LAS [LAS]",
"LELEC": "Livres électroniques en ligne [LELEC]",
"LIRCE": "LIRCES",
"LLA": "Magasins-Fonds LLAOR [LLA]",
"MAG": "Magasins [MAG]",
"MAG2": "Magasins (sous-sol) [MAG2]",
"MAN": "RDC - Manuels [MAN]",
"MED": "RDC [MED]",
"MELEC": "Mémoires électroniques",
"MEM": "Mémoires (bacs)",
"MEZA": "Mezzanine-Atlas",
"MEZO": "Mezzanine - Ouvrages anciens",
"MLC": "Magasins [MLC]",
"MM7": "Mémoires (Salle de lecture) [MM7]",
"MSH": "2e étage - bibliothèque de recherche [MSH]",
"ODONT": "RDC - Odontologie [ODONT]",
"ODYS": "RDC - Fonds Société et environnement [ODYS]",
"ORTHO": "Orthophonie [ORTHO]",
"PASS0": "Villa Passiflores (0)",
"PASS1": "Villa Passiflores (1)",
"PDCTG": "RDC (SA1) - Presse [PDCTG]",
"PDMAG": "Magasins [PDMAG]",
"PDSA0": "Sous-sol (SA0) - Revues [PDSA0]",
"PDSA1": "RDC (SA1) - Revues [PDSA1]",
"PDSA2": "Etage (SA2) - Revues [PDSA2]",
"PDSDR": "Sous-sol - Revues - Salle de recherche [PDSDR]",
"PELEC": "Périodiques électroniques [PELEC]",
"PER7": "Revues [PER7]",
"PERS": "Revues [PERS]",
"PHALL": "Hall - Périodiques [PHALL]",
"PJEC2": "2e étage - revues d'Economie et Gestion [PJEC2]",
"PJECM": "Magasins [PJECM]",
"PJECO": "1er étage [PJECO]",
"PJODM": "Magasins [PJODM]",
"PJODO": "RDC - Odontologie [PJODO]",
"PJPRS": "RDC - Presse [PJPRS]",
"PJSOC": "2e étage - revues de Sociologie [PJSOC]",
"PKINE": "RDC - Kinésithérapie [PKINE]",
"PLASE": "Magasins- Fonds ASEMI - Revues [PLASE]",
"PLIDE": "2e étage - revues Fonds IDERIC [PLIDE]",
"PLLLA": "Magasins - Fonds LLAOR - Revues [PLLA]",
"PLMG1": "Magasins - Revues [PLMG1]",
"PLMG2": "Magasins - Compactus [PLMG2]",
"PMMAG": "Magasins [PMMAG]",
"PMPAS": "Revues [PMAS]",
"PREF0": "Hall - Kiosque [PREF0]",
"PSBUR": "RDC Bureau Catalogage - Revues [PSBUR]",
"PSMG2": "Magasins - Revues [PSMG2]",
"PSNI2": "1er étage - Revues [PSNI2]",
"PSPRS": "RDC - Presse [PSPRS]",
"RDC": "Rez de chaussée",
"RE1": "RDC - Dictionnaires [RE1]",
"RE2": "1er étage - Dictionnaires [RE2]",
"REF0": "RDC - Dictionnaires [REF0]",
"REF1": "1er étage - Dictionnaires [REF1]",
"RF7": "Espace Langues [LANG7]",
"RFS": "Dictionnaires [RFS]",
"RUS": "Rustrel",
"SA0": "Sous-sol [SA0]",
"SA1": "RDC [SA1]",
"SA2": "Etage [SA2]",
"SCPO": "1er étage [SCPO]",
"SDR": "Sous-sol - Salle de recherche [SDR]",
"SHL": "RDC [SHL]",
"SL": "Salle de lecture [SL]",
"SL1": "RDC [SL1]",
"SL2": "1er étage [SL2]",
"SL7": "Salle de lecture [SL7]",
"SLC": "Salle de lecture - Collections [SLC]",
"SLO": "Salle de lecture - Ouvrages [SLO]",
"SLP": "Salle de lecture - Revues [SLP]",
"SLT": "Salle de lecture - Thèses-Mémoires [SLT]",
"SLU": "Salle de lecture - Usuels-Doc. OCA [SLU]",
"SS1O": "Sous-sol 1 - Ouvrages [SS1O]",
"SS1P": "Sous-sol 1 - Revues [SS1P]",
"SS2": "Sous-sol 2 [SS2]",
"ST": "RDC [ST]",
"TELEC": "Thèses électroniques [TELEC]",
"TH7": "Thèses (Salle de lecture) [TH7]",
"THECO": "Magasins [THECO]",
"THLAS": "Magasins [THLAS]",
"THODO": "Magasins [THODO]",
"URF": "Urfist [URF]",
"US": "Usuels [US]",
"US0": "Sous-sol (SA0) - Dictionnaires [US0]",
"US1": "RDC (SA1) - Dictionnaires [US1]",
"US2": "Etage (SA2) - Dictionnaires [US2]",
}